---
- hosts: all
  become: true
  roles:
    - common
    - containerd 
    - common-nodes

- hosts: master
  roles: 
    - master
    - role: helm
      become: true

- hosts: worker 
  roles:
    - worker
