---
## K8s Ingress Nginx
- name: Add kubernetes ingress nginx chart repo
  community.kubernetes.helm_repository:
    name: ingress-nginx
    repo_url: "https://kubernetes.github.io/ingress-nginx"

- name: Deploy latest version of kubernetes ingress nginx chart 
  community.kubernetes.helm:
    name: ingress-nginx
    chart_ref: ingress-nginx/ingress-nginx
    release_namespace: ingress-nginx
    create_namespace: true

    ## K8s Dashboard
    #- name: Add kubernetes dashboard chart repo
    #  community.kubernetes.helm_repository:
    #    name: kubernetes-dashboard
    #    repo_url: "https://kubernetes.github.io/dashboard"
    #
    #- name: Deploy latest version of kubernetes dashboard chart
    #  community.kubernetes.helm:
    #    name: kubernetes-dashboard
    #    chart_ref: kubernetes-dashboard/kubernetes-dashboard
    #    release_namespace: kube-system
    #    values: "{{ lookup('file', '../files/values-dashboard.yaml') | from_yaml }}"

# Pi Hole 
- name: Add pi-hole chart repo
  community.kubernetes.helm_repository:
    name: mojo2600
    repo_url: "https://mojo2600.github.io/pihole-kubernetes/"

- name: Deploy latest version of pihole chart
  community.kubernetes.helm:
    name: pihole
    chart_ref: mojo2600/pihole
    release_namespace: pihole
    create_namespace: true
    values: "{{ lookup('file', '../files/values-pihole.yaml') | from_yaml }}"
