---
- name: Set hostname to inventory hostname
  hostname: 
    name: "{{inventory_hostname}}"

- name: Set hosts file
  lineinfile:
    path: /etc/hosts
    regexp: '{{ item.regexp }}'
    line: '{{ item.line }}'
    state: present
  with_items:
    - { regexp: '127\.0\.1\.1.*', line: '127.0.1.1 {{ ansible_hostname }}' }

- name: enable ntp
  command: timedatectl set-ntp true

- name: start time services
  service:
    name: systemd-timesyncd
    state: started
    enabled: true

- name: Ensure GB-UTF8 locale exists
  locale_gen:
    name: en_GB.UTF-8
    state: present

- name: Copy Alias to Host
  copy:
    src:  ../files/.zshalias
    dest: /home/ubuntu/.zshalias

- name: Source de Alias
  shell: echo source /home/ubuntu/.zshalias >> /home/ubuntu/.profile

- name: apt-get upgrade
  apt:
    upgrade: full
    update_cache: true
    cache_valid_time: 3600
    force_apt_get: true
    autoclean: true
    autoremove: true
  register: apt_upgrade
  retries: 5
  until: apt_upgrade is success
  notify: Reboot
