---
- name: Initializing Kubernetes cluster
  become: true
  shell: kubeadm init --pod-network-cidr={{ k8s_network_cidr }} --apiserver-advertise-address={{ k8s_apiserver }}
  register: output
  
- name: storing logs and generated token for future purpose.
  local_action: copy content="{{ output.stdout }}" dest="{{ token_file }}"
 
- name: configure k8s and weave cni
  script: ../files/k8s-config.sh 

- name: Copy Kubeconfig to local
  become: true
  fetch:
    src: /etc/kubernetes/admin.conf
    dest: ~/.kube/config
    flat: yes
