---
- name: Initializing Kubernetes cluster
  become: true
  shell: kubeadm init --pod-network-cidr={{ k8s_network_cidr }} --apiserver-advertise-address={{ k8s_apiserver }}
  register: output
  
- name: storing logs and generated token for future purpose.
  local_action: copy content="{{ output.stdout }}" dest="{{ token_file }}"
 
- name: configure k8s and weave cni
  script: ../files/k8s-config.sh 

- name: Copy Kubeconfig to local
  become: true
  fetch:
    src: /etc/kubernetes/admin.conf
    dest: ~/.kube/config
    flat: yes

# helm install 
- name: Add apt-key of helm
  become: true
  apt_key:
    url: https://baltocdn.com/helm/signing.asc
    state: present

- name: Add helm repository
  become: true
  apt_repository:
    repo: deb https://baltocdn.com/helm/stable/debian/ all main
    state: present

- name: Update repositories cache and install helm
  become: true
  apt:
    name: helm
    update_cache: yes
