---
- name: Install docker dependencies
  apt:
    name: "{{ packages }}"
    state: present
    update_cache: yes
  vars:
    packages:
    - apt-transport-https
    - ca-certificates
    - curl
    - software-properties-common
    - gnupg2
    - gnupg-agent

- name: Add docker repo apt key
  apt_key:
    url: "{{ docker_apt_key }}"
    state: present

- name: Add Docker repository
  apt_repository:
    repo: "{{ docker_apt_repository }}"
    state: present

- name: apt-get update 
  apt: 
    update_cache: yes 
    upgrade: safe

- name: Install docker
  package:
    name: "{{ packages }}"
    state: present 
  vars:
    packages:
    - docker-ce 
    - docker-ce-cli 
    - containerd.io

- name: Prepare default daemon configuration
  copy:
    src:  ../files/daemon.json
    dest: /etc/docker/daemon.json

- name: Create systemd configuration directory for Docker service (systemd)
  file:
    dest: /etc/systemd/system/docker.service.d
    state: directory
    owner: root
    group: root
    mode: 0755
  notify: 
    - reload systemd
    - restart docker
    - enable docker

- name: Set periodic docker system prune
  cron:
    name: docker-prune
    minute: "0"
    hour: "*/2"
    job: docker container prune -f

- name: Add users to docker group
  user:
    name: "{{ docker_group_members }}"
    groups: docker
    append: yes
  when: docker_group_members is defined
